### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by szugyiedit** [RoshanRane/PredNet-and-Predictive-Coding-A-Critical-Review#14]
Research about the following datasets : 
1) something-something-v2
2) UCF-101
3) HMDB-51
4) Sports-1M
5) YouTube-8M
6) KITTI dataset

Things to find out for all the datasets :
1) Total videos
2) fps and the resolution of each frame of the videos
3) Check out few videos and list anything peculiar (like changing cameras within a video).

**Comment by applepieiris** [comment]
> 

http://bigvid.fudan.edu.cn/FCVID/
the link is broken?
